import { expression } from "@babel/template";


export const technologies = [ 
  {name: 'JavaScript',
   category: 'languages',
   related: ['React', 'Redux', 'Node'],
   extras: ''},
  {name: 'React',
   category: 'frameworks',
   related: ['React Native', 'Redux', 'Vue', 'JavaScript'],
   extras: ''},
  {name: 'Redux',
   category: 'libraries',
   related: ['React'],
   extras: ''},
  {name: 'Node',
   category: 'server-side',
   related: ['Node', 'JavaScript'],
   extras: ''},
  {name: 'HTML',
   category: 'basics',
   related: ['CSS', 'jQuery'],
   extras: ''},
  {name: 'CSS',
   category: 'basics',
   related: ['Sass', 'HTML', 'Responsive Design'],
   extras: ''},
  {name: 'React Native',
   category: 'frameworks',
   related: ['React', 'JavaScript'],
   extras: ''},
  {name: 'Vue',
   category: 'frameworks',
   related: ['JavaScript', 'React'],
   extras: ''},
  {name: 'Electron',
   category: 'frameworks',
   related: ['JavaScript'],
   extras: ''},
  {name: 'jQuery',
   category: 'libraries',
   related: ['JavaScript'],
   extras: ''},
  {name: 'Sass',
   category: '',
   related: ['CSS', 'Bootstrap'],
   extras: ''},
  {name: 'Bootstrap',
   category: 'frameworks',
   related: ['CSS, Sass'],
   extras: ''},
  {name: 'Mocha',
   category: 'tdd',
   related: ['Chai', 'Jest', 'Enzyme'],
   extras: ''},
  {name: 'Chai',
   category: 'tdd',
   related: ['Mocha', 'Jest', 'Enzyme'],
   extras: ''},
  {name: 'Jest',
   category: 'tdd',
   related: ['Mocha', 'Chai', 'Enzyme'],
   extras: ''},
  {name: 'Enzyme',
   category: 'tdd',
   related: ['Mocha', 'Chai', 'Jest'],
   extras: ''},
  {name: 'SQL',
   category: 'languages',
   related: ['server-side'],
   extras: ''},
  {name: 'Express',
   category: 'server-side',
   related: ['Node'],
   extras: ''},
  {name: 'Knex',
   category: 'server-side',
   related: ['Express', 'SQL'],
   extras: ''},
  {name: 'REST APIs',
   category: '',
   related: [],
   extras: ''},
  {name: 'Git',
   category: 'version control',
   related: ['GitHub'],
   extras: ''},
  {name: 'GitHub',
   category: 'version control',
   related: ['Git'],
   extras: ''}
]

