import { expression } from "@babel/template";


export const technologies = [ 
  {name: 'JavaScript',
   category: 'languages',
   related: ['React', 'Redux', 'NodeJS'],
   extras: ''},
  {name: 'React',
   category: 'frameworks',
   related: ['React Native', 'Redux', 'Vue', 'JavaScript'],
   extras: ''},
  {name: 'Redux',
   category: 'libraries',
   related: ['React'],
   extras: ''},
  {name: 'Node.js',
   category: 'server-side',
   related: ['JavaScript'],
   extras: ''},
  {name: 'HTML',
   category: 'basics',
   related: ['CSS', 'jQuery'],
   extras: ''},
  {name: 'CSS',
   category: 'basics',
   related: ['Sass', 'HTML', 'Responsive Design'],
   extras: ''},
  {name: 'React Native',
   category: 'frameworks',
   related: ['React', 'JavaScript'],
   extras: ''},
  {name: 'Vue',
   category: 'frameworks',
   related: ['JavaScript', 'React'],
   extras: ''},
  {name: 'Electron',
   category: 'frameworks',
   related: ['JavaScript'],
   extras: ''},
  {name: 'jQuery',
   category: 'libraries',
   related: ['JavaScript'],
   extras: ''},
  {name: 'Sass',
   category: '',
   related: ['CSS', 'Bootstrap'],
   extras: ''},
  {name: 'Bootstrap',
   category: 'frameworks',
   related: ['CSS, Sass'],
   extras: ''},
  {name: 'Mocha',
   category: '',
   related: [],
   extras: ''},
  {name: 'Chai',
   category: '',
   related: [],
   extras: ''},
  {name: 'Jest',
   category: '',
   related: [],
   extras: ''},
  {name: 'Enzyme',
   category: '',
   related: [],
   extras: ''},
  {name: 'SQL',
   category: '',
   related: [],
   extras: ''},
  {name: 'Express',
   category: '',
   related: [],
   extras: ''},
  {name: 'Knex',
   category: '',
   related: [],
   extras: ''},
  {name: 'REST APIs',
   category: '',
   related: [],
   extras: ''},
  {name: 'Git',
   category: '',
   related: [],
   extras: ''},
  {name: 'GitHub',
   category: '',
   related: [],
   extras: ''},
  {name: 'Responsive Design',
   category: '',
   related: [],
   extras: ''},
   
]

